// <auto-generated />
namespace EFCore.FSharp.AuthMvc.Migrations

open System
open EFCore.FSharp.AuthMvc.Data
open Microsoft.EntityFrameworkCore
open Microsoft.EntityFrameworkCore.Infrastructure
open Microsoft.EntityFrameworkCore.Metadata
open Microsoft.EntityFrameworkCore.Migrations
open Microsoft.EntityFrameworkCore.Storage.ValueConversion

[<DbContext(typeof<ApplicationDbContext>)>]
[<Migration("20210320163652_Initial")>]
type Initial() =
    inherit Migration()

    override this.Up(migrationBuilder:MigrationBuilder) =
        migrationBuilder.CreateTable(
            name = "AspNetRoles"
            ,columns = (fun table -> 
            {|
                Id =
                    table.Column<string>(
                        nullable = false
                        ,``type`` = "nvarchar(450)"
                    )
                Name =
                    table.Column<string>(
                        nullable = true
                        ,``type`` = "nvarchar(256)"
                        , maxLength = Nullable(256))
                NormalizedName =
                    table.Column<string>(
                        nullable = true
                        ,``type`` = "nvarchar(256)"
                        , maxLength = Nullable(256))
                ConcurrencyStamp =
                    table.Column<string>(
                        nullable = true
                        ,``type`` = "nvarchar(max)"
                    )
            |})
        ) |> ignore

        migrationBuilder.CreateTable(
            name = "AspNetUsers"
            ,columns = (fun table -> 
            {|
                Id =
                    table.Column<string>(
                        nullable = false
                        ,``type`` = "nvarchar(450)"
                    )
                UserName =
                    table.Column<string>(
                        nullable = true
                        ,``type`` = "nvarchar(256)"
                        , maxLength = Nullable(256))
                NormalizedUserName =
                    table.Column<string>(
                        nullable = true
                        ,``type`` = "nvarchar(256)"
                        , maxLength = Nullable(256))
                Email =
                    table.Column<string>(
                        nullable = true
                        ,``type`` = "nvarchar(256)"
                        , maxLength = Nullable(256))
                NormalizedEmail =
                    table.Column<string>(
                        nullable = true
                        ,``type`` = "nvarchar(256)"
                        , maxLength = Nullable(256))
                EmailConfirmed =
                    table.Column<bool>(
                        nullable = false
                        ,``type`` = "bit"
                    )
                PasswordHash =
                    table.Column<string>(
                        nullable = true
                        ,``type`` = "nvarchar(max)"
                    )
                SecurityStamp =
                    table.Column<string>(
                        nullable = true
                        ,``type`` = "nvarchar(max)"
                    )
                ConcurrencyStamp =
                    table.Column<string>(
                        nullable = true
                        ,``type`` = "nvarchar(max)"
                    )
                PhoneNumber =
                    table.Column<string>(
                        nullable = true
                        ,``type`` = "nvarchar(max)"
                    )
                PhoneNumberConfirmed =
                    table.Column<bool>(
                        nullable = false
                        ,``type`` = "bit"
                    )
                TwoFactorEnabled =
                    table.Column<bool>(
                        nullable = false
                        ,``type`` = "bit"
                    )
                LockoutEnd =
                    table.Column<DateTimeOffset>(
                        nullable = true
                        ,``type`` = "datetimeoffset"
                    )
                LockoutEnabled =
                    table.Column<bool>(
                        nullable = false
                        ,``type`` = "bit"
                    )
                AccessFailedCount =
                    table.Column<int>(
                        nullable = false
                        ,``type`` = "int"
                    )
            |})
        ) |> ignore

        migrationBuilder.CreateTable(
            name = "AspNetRoleClaims"
            ,columns = (fun table -> 
            {|
                Id =
                    table.Column<int>(
                        nullable = false
                        ,``type`` = "int"
                    )
                        .Annotation("SqlServer:Identity", "1, 1")
                RoleId =
                    table.Column<string>(
                        nullable = false
                        ,``type`` = "nvarchar(450)"
                    )
                ClaimType =
                    table.Column<string>(
                        nullable = true
                        ,``type`` = "nvarchar(max)"
                    )
                ClaimValue =
                    table.Column<string>(
                        nullable = true
                        ,``type`` = "nvarchar(max)"
                    )
            |})
        ) |> ignore

        migrationBuilder.CreateTable(
            name = "AspNetUserClaims"
            ,columns = (fun table -> 
            {|
                Id =
                    table.Column<int>(
                        nullable = false
                        ,``type`` = "int"
                    )
                        .Annotation("SqlServer:Identity", "1, 1")
                UserId =
                    table.Column<string>(
                        nullable = false
                        ,``type`` = "nvarchar(450)"
                    )
                ClaimType =
                    table.Column<string>(
                        nullable = true
                        ,``type`` = "nvarchar(max)"
                    )
                ClaimValue =
                    table.Column<string>(
                        nullable = true
                        ,``type`` = "nvarchar(max)"
                    )
            |})
        ) |> ignore

        migrationBuilder.CreateTable(
            name = "AspNetUserLogins"
            ,columns = (fun table -> 
            {|
                LoginProvider =
                    table.Column<string>(
                        nullable = false
                        ,``type`` = "nvarchar(128)"
                        , maxLength = Nullable(128))
                ProviderKey =
                    table.Column<string>(
                        nullable = false
                        ,``type`` = "nvarchar(128)"
                        , maxLength = Nullable(128))
                ProviderDisplayName =
                    table.Column<string>(
                        nullable = true
                        ,``type`` = "nvarchar(max)"
                    )
                UserId =
                    table.Column<string>(
                        nullable = false
                        ,``type`` = "nvarchar(450)"
                    )
            |})
        ) |> ignore

        migrationBuilder.CreateTable(
            name = "AspNetUserRoles"
            ,columns = (fun table -> 
            {|
                UserId =
                    table.Column<string>(
                        nullable = false
                        ,``type`` = "nvarchar(450)"
                    )
                RoleId =
                    table.Column<string>(
                        nullable = false
                        ,``type`` = "nvarchar(450)"
                    )
            |})
        ) |> ignore

        migrationBuilder.CreateTable(
            name = "AspNetUserTokens"
            ,columns = (fun table -> 
            {|
                UserId =
                    table.Column<string>(
                        nullable = false
                        ,``type`` = "nvarchar(450)"
                    )
                LoginProvider =
                    table.Column<string>(
                        nullable = false
                        ,``type`` = "nvarchar(128)"
                        , maxLength = Nullable(128))
                Name =
                    table.Column<string>(
                        nullable = false
                        ,``type`` = "nvarchar(128)"
                        , maxLength = Nullable(128))
                Value =
                    table.Column<string>(
                        nullable = true
                        ,``type`` = "nvarchar(max)"
                    )
            |})
        ) |> ignore

        migrationBuilder.CreateIndex(
            name = "IX_AspNetRoleClaims_RoleId"
            ,table = "AspNetRoleClaims"
            ,column = "RoleId"
            ) |> ignore

        migrationBuilder.CreateIndex(
            name = "RoleNameIndex"
            ,table = "AspNetRoles"
            ,column = "NormalizedName"
            ,unique = true
            ,filter = "[NormalizedName] IS NOT NULL"
            ) |> ignore

        migrationBuilder.CreateIndex(
            name = "IX_AspNetUserClaims_UserId"
            ,table = "AspNetUserClaims"
            ,column = "UserId"
            ) |> ignore

        migrationBuilder.CreateIndex(
            name = "IX_AspNetUserLogins_UserId"
            ,table = "AspNetUserLogins"
            ,column = "UserId"
            ) |> ignore

        migrationBuilder.CreateIndex(
            name = "IX_AspNetUserRoles_RoleId"
            ,table = "AspNetUserRoles"
            ,column = "RoleId"
            ) |> ignore

        migrationBuilder.CreateIndex(
            name = "EmailIndex"
            ,table = "AspNetUsers"
            ,column = "NormalizedEmail"
            ) |> ignore

        migrationBuilder.CreateIndex(
            name = "UserNameIndex"
            ,table = "AspNetUsers"
            ,column = "NormalizedUserName"
            ,unique = true
            ,filter = "[NormalizedUserName] IS NOT NULL"
            ) |> ignore


    override this.Down(migrationBuilder:MigrationBuilder) =
        migrationBuilder.DropTable(
            name = "AspNetRoleClaims"
            ) |> ignore

        migrationBuilder.DropTable(
            name = "AspNetUserClaims"
            ) |> ignore

        migrationBuilder.DropTable(
            name = "AspNetUserLogins"
            ) |> ignore

        migrationBuilder.DropTable(
            name = "AspNetUserRoles"
            ) |> ignore

        migrationBuilder.DropTable(
            name = "AspNetUserTokens"
            ) |> ignore

        migrationBuilder.DropTable(
            name = "AspNetRoles"
            ) |> ignore

        migrationBuilder.DropTable(
            name = "AspNetUsers"
            ) |> ignore


    override this.BuildTargetModel(modelBuilder: ModelBuilder) =
        modelBuilder

            .UseIdentityColumns().HasAnnotation("Relational:MaxIdentifierLength", 128)
            .HasAnnotation("ProductVersion", "5.0.3")
            |> ignore

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", (fun b ->

            b.Property<string>("Id")
                .HasColumnType("nvarchar(450)") |> ignore
            b.Property<string>("ConcurrencyStamp")
                .IsConcurrencyToken()
                .HasColumnType("nvarchar(max)") |> ignore
            b.Property<string>("Name")
                .HasMaxLength(256)
                .HasColumnType("nvarchar(256)") |> ignore
            b.Property<string>("NormalizedName")
                .HasMaxLength(256)
                .HasColumnType("nvarchar(256)") |> ignore

            b.HasKey("Id") |> ignore


            b.HasIndex("NormalizedName")
                .IsUnique()
                .HasDatabaseName("RoleNameIndex")
                .HasFilter("[NormalizedName] IS NOT NULL") |> ignore

            b.ToTable("AspNetRoles") |> ignore

        )) |> ignore

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", (fun b ->

            b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("int")
                .UseIdentityColumn() |> ignore
            b.Property<string>("ClaimType")
                .HasColumnType("nvarchar(max)") |> ignore
            b.Property<string>("ClaimValue")
                .HasColumnType("nvarchar(max)") |> ignore
            b.Property<string>("RoleId")
                .IsRequired()
                .HasColumnType("nvarchar(450)") |> ignore

            b.HasKey("Id") |> ignore


            b.HasIndex("RoleId") |> ignore

            b.ToTable("AspNetRoleClaims") |> ignore

        )) |> ignore

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", (fun b ->

            b.Property<string>("Id")
                .HasColumnType("nvarchar(450)") |> ignore
            b.Property<int>("AccessFailedCount")
                .IsRequired()
                .HasColumnType("int") |> ignore
            b.Property<string>("ConcurrencyStamp")
                .IsConcurrencyToken()
                .HasColumnType("nvarchar(max)") |> ignore
            b.Property<string>("Email")
                .HasMaxLength(256)
                .HasColumnType("nvarchar(256)") |> ignore
            b.Property<bool>("EmailConfirmed")
                .IsRequired()
                .HasColumnType("bit") |> ignore
            b.Property<bool>("LockoutEnabled")
                .IsRequired()
                .HasColumnType("bit") |> ignore
            b.Property<Nullable<DateTimeOffset>>("LockoutEnd")
                .HasColumnType("datetimeoffset") |> ignore
            b.Property<string>("NormalizedEmail")
                .HasMaxLength(256)
                .HasColumnType("nvarchar(256)") |> ignore
            b.Property<string>("NormalizedUserName")
                .HasMaxLength(256)
                .HasColumnType("nvarchar(256)") |> ignore
            b.Property<string>("PasswordHash")
                .HasColumnType("nvarchar(max)") |> ignore
            b.Property<string>("PhoneNumber")
                .HasColumnType("nvarchar(max)") |> ignore
            b.Property<bool>("PhoneNumberConfirmed")
                .IsRequired()
                .HasColumnType("bit") |> ignore
            b.Property<string>("SecurityStamp")
                .HasColumnType("nvarchar(max)") |> ignore
            b.Property<bool>("TwoFactorEnabled")
                .IsRequired()
                .HasColumnType("bit") |> ignore
            b.Property<string>("UserName")
                .HasMaxLength(256)
                .HasColumnType("nvarchar(256)") |> ignore

            b.HasKey("Id") |> ignore


            b.HasIndex("NormalizedEmail")
                .HasDatabaseName("EmailIndex") |> ignore


            b.HasIndex("NormalizedUserName")
                .IsUnique()
                .HasDatabaseName("UserNameIndex")
                .HasFilter("[NormalizedUserName] IS NOT NULL") |> ignore

            b.ToTable("AspNetUsers") |> ignore

        )) |> ignore

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", (fun b ->

            b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("int")
                .UseIdentityColumn() |> ignore
            b.Property<string>("ClaimType")
                .HasColumnType("nvarchar(max)") |> ignore
            b.Property<string>("ClaimValue")
                .HasColumnType("nvarchar(max)") |> ignore
            b.Property<string>("UserId")
                .IsRequired()
                .HasColumnType("nvarchar(450)") |> ignore

            b.HasKey("Id") |> ignore


            b.HasIndex("UserId") |> ignore

            b.ToTable("AspNetUserClaims") |> ignore

        )) |> ignore

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", (fun b ->

            b.Property<string>("LoginProvider")
                .HasMaxLength(128)
                .HasColumnType("nvarchar(128)") |> ignore
            b.Property<string>("ProviderKey")
                .HasMaxLength(128)
                .HasColumnType("nvarchar(128)") |> ignore
            b.Property<string>("ProviderDisplayName")
                .HasColumnType("nvarchar(max)") |> ignore
            b.Property<string>("UserId")
                .IsRequired()
                .HasColumnType("nvarchar(450)") |> ignore

            b.HasKey("LoginProvider", "ProviderKey") |> ignore


            b.HasIndex("UserId") |> ignore

            b.ToTable("AspNetUserLogins") |> ignore

        )) |> ignore

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", (fun b ->

            b.Property<string>("UserId")
                .HasColumnType("nvarchar(450)") |> ignore
            b.Property<string>("RoleId")
                .HasColumnType("nvarchar(450)") |> ignore

            b.HasKey("UserId", "RoleId") |> ignore


            b.HasIndex("RoleId") |> ignore

            b.ToTable("AspNetUserRoles") |> ignore

        )) |> ignore

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", (fun b ->

            b.Property<string>("UserId")
                .HasColumnType("nvarchar(450)") |> ignore
            b.Property<string>("LoginProvider")
                .HasMaxLength(128)
                .HasColumnType("nvarchar(128)") |> ignore
            b.Property<string>("Name")
                .HasMaxLength(128)
                .HasColumnType("nvarchar(128)") |> ignore
            b.Property<string>("Value")
                .HasColumnType("nvarchar(max)") |> ignore

            b.HasKey("UserId", "LoginProvider", "Name") |> ignore

            b.ToTable("AspNetUserTokens") |> ignore

        )) |> ignore

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", (fun b ->
            b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole",null)
                .WithMany()
                .HasForeignKey("RoleId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired() |> ignore
        )) |> ignore

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", (fun b ->
            b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser",null)
                .WithMany()
                .HasForeignKey("UserId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired() |> ignore
        )) |> ignore

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", (fun b ->
            b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser",null)
                .WithMany()
                .HasForeignKey("UserId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired() |> ignore
        )) |> ignore

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", (fun b ->
            b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole",null)
                .WithMany()
                .HasForeignKey("RoleId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired() |> ignore
            b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser",null)
                .WithMany()
                .HasForeignKey("UserId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired() |> ignore
        )) |> ignore

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", (fun b ->
            b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser",null)
                .WithMany()
                .HasForeignKey("UserId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired() |> ignore
        )) |> ignore

